cas:
  enabled: true
  login_success_url: /sdfsfdsfsfsfrdsf
  base_url: _
  server_url: http://localhost:8080
  service_validate_url: ${cas.base_url}/cas/serviceValidate
  login_url: ${cas.base_url}/cas/login?service=${cas.callback_url}
  logout_url: ${cas.base_url}/cas/logout?service=${cas.callback_url}
  callback_url: ${cas.server_url}/cas/callback
  ignore_path:
    - /static/**
    - /favicon.ico
    - /error
